#######################################################################################
# Book settings
title : PPOL 574/Data Science 1 Fall 2022
author: Rebecca Johnson
logo: 'laptop.png'

# Information about where the book exists on the web
description: >-
  This is the syllabus for the fall 2022 PPOL 574/Data Science 1 at Georgetown's McCourt School of Public Policy. 

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/executablebooks/quantecon-mini-example
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex